name: Metrics
on:
    schedule: [{ cron: "0 * * * *" }]
    workflow_dispatch:
    push: { branches: ["master", "main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: permafrozen
                  template: markdown
                  filename: README.md
                  markdown: >-
                      https://raw.githubusercontent.com/Permafrozen/Permafrozen/refs/heads/main/markdown-template.md
                  config_output: markdown
